Unidriver
irsural/mxsrclib pull request #2
Opened 2024-03-01 07:27 UTC by Prodiks

2024-03-27 05:20 UTC, Feelinglight requested changes

2024-03-27 05:20 UTC, Feelinglight commented on csvwork.cpp
> +    a_elem_array.emplace_back(name_str, a_elem);
Так не делаем, в mxsrclib только C++03

2024-03-27 05:20 UTC, Feelinglight commented on hardflowg.cpp
> +        } [[fallthrough]]; // TODO: �� ������ ����� �� ������� break
С++03

2024-03-27 05:20 UTC, Feelinglight commented on hardflowg.cpp
> +string narrow( const string& str )
Это где-то используется?

2024-03-27 05:20 UTC, Feelinglight commented on irsadc.cpp
> +    } [[fallthrough]]; // TODO: �� ������ ����� �� ������� break
C++03

2024-03-27 05:20 UTC, Feelinglight commented on irscalc.cpp
> +[[maybe_unused]]
C++03

2024-03-27 05:20 UTC, Feelinglight commented on irseeprom.cpp
> +  mp_buffer(nullptr),
C++03

2024-03-27 05:20 UTC, Feelinglight commented on irsfilter.h
> +        [[fallthrough]]; // TODO: �� ������ ����� �� break
C++03

2024-03-27 05:20 UTC, Feelinglight commented on irsfilter.h
> +      [[fallthrough]]; // TODO: �� ������ ����� �� break
C++03

2024-03-27 05:20 UTC, Feelinglight commented on irsvariant.h
> +      [[fallthrough]]; // TODO: �� ������ ����� �� ������� break
C++03

2024-03-27 05:20 UTC, Feelinglight commented on niusbgpib_hardflow.cpp
> +[[maybe_unused]]
C++03

2024-03-27 05:20 UTC, Feelinglight commented on irsstring.h
> +  IRS_STRING_TYPE& operator=(const IRS_STRING_TYPE& strg)
Это где-то используется?

2024-03-27 05:20 UTC, Feelinglight commented on irssysutils.h
> +      const int first_part = hex_data_map[static_cast<unsigned int>(a_str[elem_i])];
size_type?

2024-03-27 05:20 UTC, Feelinglight commented on mxdata.h
> -//! \file
Слегка многовато изменений в этом файле

2024-06-05 06:52 UTC, Prodiks commented on hardflowg.cpp
> +string narrow( const string& str )
В этом же файле используется если не WIN32.
Я так понимаю, если нет define UNICODE, то компилятор пытается найти перегрузку для std::string.

2024-06-05 07:00 UTC, Prodiks commented on irsstring.h
> +  IRS_STRING_TYPE& operator=(const IRS_STRING_TYPE& strg)
Неявно создан оператор присваивания копированием, потому что объявлен конструктор копирования.

```
 warning: implicitly-declared ‘irs::basic_irs_string_t<char>& irs::basic_irs_string_t<char>::operator=(const irs::basic_irs_string_t<char>&)’ is deprecated [
-Wdeprecated-copy]
```

2024-06-05 07:10 UTC, Prodiks commented on irssysutils.h
> +      const int first_part = hex_data_map[static_cast<unsigned int>(a_str[elem_i])];
Заменил на unsigned char.

2024-06-06 08:03 UTC, Feelinglight requested changes

2024-06-06 08:03 UTC, Feelinglight commented on CMakeLists.txt
> +        arch/qt/irsdefsarch.h
Дима скоро смерджит свой cmake и тебе нужно будет влить его к себе.
Ждем его.

2024-06-06 08:03 UTC, Feelinglight commented on CMakeLists.txt
> +        irseeprom.cpp
Все cpp нужны? Нужно оставить как можно меньше, а то Дима там умрет компилировать под gcc все это добро

2024-06-07 13:15 UTC, Feelinglight commented on CMakeLists.txt
> +        arch/qt/irsdefsarch.h
@Prodiks смерджил, можно вливать

2024-06-10 13:37 UTC, Feelinglight approved these changes

2024-06-10 13:37 UTC, merged