Добавлена поддержка таймера на stm32f746 на gcc
irsural/mxsrclib pull request #3
Opened 2024-05-22 11:35 UTC by injecktor

2024-05-23 05:58 UTC, Feelinglight requested changes

2024-05-23 05:58 UTC, Feelinglight commented on irscpu.cpp
> +#ifdef IRS_STM32_F2_F4_F7
У тебя F7 и этот дефайн должен быть у тебя объявлен.

Так что если ты эти переменные убрал этим дефайном, то это неправильно

2024-05-23 06:34 UTC, injecktor commented on irscpu.cpp
> +#ifdef IRS_STM32_F2_F4_F7
Эти переменные в [irscpu.h](https://github.com/irsural/mxsrclib/blob/master/irscpu.h#L39) объявляются
только с учетом этого дефайна. Так что правильнее так же сделать и для остальных случаев.

2024-05-23 06:51 UTC, Feelinglight commented on irscpu.cpp
> +#ifdef IRS_STM32_F2_F4_F7
У тебя F7? Значит этот дефайн должен быть определен у тебя в проекте. Иначе куча функций из mxsrclib будут для тебя недоступны. То что ты сделал - затычка, которая работает в этом конкретном случае, да еще и выносит мозг

2024-05-23 10:08 UTC, injecktor commented
@Feelinglight Убрал лишний файл

2024-05-24 03:51 UTC, Feelinglight approved these changes

2024-05-24 03:51 UTC, merged