Добавлен файл конвертации из cp1251 в utf-8
irsural/mxsrclib pull request #4
Opened 2024-05-28 13:47 UTC by injecktor

2024-05-29 02:45 UTC, Prodiks commented on convert_mxsrclib_headers/CMakeLists.txt
> +    set(DEST "${SOURCE_DIR}/mxsrclib_utf-8")
Это относительно исходников проекта или mxsrclib?

2024-05-29 06:08 UTC, injecktor commented on convert_mxsrclib_headers/CMakeLists.txt
> +    set(DEST "${SOURCE_DIR}/mxsrclib_utf-8")
Внутри папки mxsrclib создается папка mxsrclib_utf-8.

Переменная SOURCE_DIR хранит в себе путь до родительской директории cmake'а

2024-05-30 07:17 UTC, Prodiks approved these changes

2024-05-30 08:25 UTC, Feelinglight requested changes

2024-05-30 08:25 UTC, Feelinglight commented on convert_mxsrclib_headers/CMakeLists.txt
> +include(FindIconv)
Добавить пустые строки между логическими блоками

2024-05-30 08:25 UTC, Feelinglight commented on convert_mxsrclib_headers/CMakeLists.txt
> +    message("Error iconv not found")
Если у меня проект в 1251, то мне не нужен iconv

2024-05-30 08:25 UTC, Feelinglight commented on convert_mxsrclib_headers/CMakeLists.txt
> +file(GLOB_RECURSE ORIGIN_HEADER_PATH_LIST_arch_arm "${SOURCE_DIR}/arch/arm/*.h")
Зачем все инклуды? Они взаимоимключающие. Сделать переменную, по которой выбирать нужные.

2024-05-30 08:25 UTC, Feelinglight commented on convert_mxsrclib_headers/CMakeLists.txt
> +# Если небыли переданы аргументы, то задаются стандартные значения
От слова небылица или как? 😁

2024-05-30 08:25 UTC, Feelinglight commented on convert_mxsrclib_headers/CMakeLists.txt
> +if(NOT DEFINED UTF8_MXSRCLIB_HEADERS_DIR)
У этого есть практический смысл?

2024-05-30 08:25 UTC, Feelinglight commented on convert_mxsrclib_headers/CMakeLists.txt
> +include(FindIconv)
Добавить документацию по стандартному шаблону sphinx, где кратко объяснить сборку и зачем нужны танцы с бубном ниже

2024-05-30 09:10 UTC, injecktor commented on convert_mxsrclib_headers/CMakeLists.txt
> +if(NOT DEFINED UTF8_MXSRCLIB_HEADERS_DIR)
Тимофей сказал добавить эту переменную.

2024-05-30 09:34 UTC, injecktor commented on convert_mxsrclib_headers/CMakeLists.txt
> +    message("Error iconv not found")
Если проект в 1251, то этот cmake вообще не нужно подключать

2024-05-31 04:56 UTC, Feelinglight commented on convert_mxsrclib_headers/CMakeLists.txt
> +if (NOT DEFINED INCLUDE_ARCH)
``MXSRCLIB_ARCH``

2024-05-31 04:56 UTC, Feelinglight commented on convert_mxsrclib_headers/CMakeLists.txt
> +    message("Error iconv not found")
Да ладно. Это ты как увидел связь между кодировкой и системой сборки?

2024-05-31 05:20 UTC, Feelinglight commented on convert_mxsrclib_headers/CMakeLists.txt
> +if(NOT DEFINED UTF8_MXSRCLIB_HEADERS_DIR)
Поговорил с Тимофеем, переменную можно убрать. Сконвертированные исходники всегда в папке mxsrclib

2024-06-03 05:32 UTC, Prodiks requested changes

2024-06-03 05:32 UTC, tpryaminin commented on CMakeLists.txt
> +if(NOT DEFINED MXSRCLIB_CONVERT_SYMBOL_ENCODING)
Название сбивает с толку, ведь конвертация всегда происходит из cp1251 в utf-8.
Сделать это флагом и назвать CONVERT_HEADERS. 
По умолчанию - False.

2024-06-03 05:32 UTC, Prodiks commented on CMakeLists.txt
> +    set(CONVERTED_MXSRCLIB_HEADERS ${MXSRCLIB_HEADERS_DIR})
Получается запутанно, ведь в этом случае это `CONVERTED_MXSRCLIB_HEADERS  `это вовсе не сконвертированные заголовки. Сделать так:
```
if (${CONVERT_HEADERS})
    ...
    target_include_directories(mxsrclib INTERFACE ${CONVERTED_MXSRCLIB_HEADERS})
else()
    ...
    target_include_directories(mxsrclib INTERFACE ${MXSRCLIB_HEADERS})
```

2024-06-03 05:32 UTC, Prodiks commented on convert_mxsrclib_headers/CMakeLists.txt
> +set(CONVERTED_MXSRCLIB_HEADERS_DIR "${MXSRCLIB_DIR}/mxsrclib_${MXSRCLIB_CONVERT_SYMBOL_ENCODING}")
Если MXSRCLIB_CONVERT_SYMBOL_ENCODING не UTF-8 и не CP1251, то возникнет ошибка. При этом, если MXSRCLIB_CONVERT_SYMBOL_ENCODING = CP1251 то этот скрипт вообще не отработает. 
И у iconv'а параметры заданы константами, так какой в этом смысл?

Возможно стоит переимновать convert_mxsrclib_headers в converted_headers, и складывать сконвертированные заголовки сразу туда.

2024-06-03 06:13 UTC, injecktor commented on convert_mxsrclib_headers/CMakeLists.txt
> +set(CONVERTED_MXSRCLIB_HEADERS_DIR "${MXSRCLIB_DIR}/mxsrclib_${MXSRCLIB_CONVERT_SYMBOL_ENCODING}")
> Если MXSRCLIB_CONVERT_SYMBOL_ENCODING не UTF-8 и не CP1251, то возникнет ошибка. При этом, если MXSRCLIB_CONVERT_SYMBOL_ENCODING = CP1251 то этот скрипт вообще не отработает.

Я оставил возможность дальнейшего добавления других кодировок.

> И у iconv'а параметры заданы константами, так какой в этом смысл?

Так как на данный момент конвертация только в utf-8, можно задать константой.

2024-06-04 02:53 UTC, Prodiks requested changes

2024-06-04 02:53 UTC, tpryaminin commented on converted_headers/CMakeLists.txt
> +set(CONVERTED_MXSRCLIB_HEADERS_DIR "${MXSRCLIB_DIR}/mxsrclib_utf8")
"${MXSRCLIB_DIR}/converted_headers

2024-06-04 02:53 UTC, Prodiks commented on docs/src/docs.md
> +- **MXSRCLIB_CONVERT_SYMBOL_ENCODING**
Не актуально. Написать про флаг CONVERT_HEADERS.

2024-06-04 02:53 UTC, Prodiks commented on docs/src/docs.md
> +  Стандартное значение: **none**
Если оно обязательное, зачем тогда значение по умолчанию?

2024-06-04 02:53 UTC, Prodiks commented on CMakeLists.txt
> +            "${CONVERTED_MXSRCLIB_HEADERS_DIR}/arch/${MXSRCLIB_ARCH}"
Что произойдет если MXSRCLIB_ARCH по умолчанию, т.е. "none". Зачем вообще может быть нужно значение "none" этой переменной?

2024-06-04 06:07 UTC, injecktor commented on CMakeLists.txt
> +            "${CONVERTED_MXSRCLIB_HEADERS_DIR}/arch/${MXSRCLIB_ARCH}"
Нечего не произойдет. Он попытается найти эту папку, не найдет, заигнорит, и все будет работать.

Но все равно добавил if на этот случай

2024-06-04 09:38 UTC, Prodiks approved these changes

2024-06-04 11:26 UTC, Feelinglight requested changes

2024-06-04 11:26 UTC, Feelinglight commented on converted_headers/CMakeLists.txt
> +include(FindIconv)
назвать папку utf8_headers

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +if(NOT DEFINED CONVERT_HEADERS)
При чем тут headers?
Клиенту вся библиотека нужна в utf8.
Назвать MXSRCLIB_UTF8

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +    message(FATAL_ERROR "Compiler must be selected.")
Любые сообщения по русски

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +    message(FATAL_ERROR "Unable to find irsconfig file.")
Да ты тут и не пытаешься ничего найти. Ошибка в том что не задан параметр, а не в том что что-то там не находится

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +    message(STATUS "MXSRCLIB_ARCH: ${MXSRCLIB_ARCH}")
Зачем?

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +        NOT (MXSRCLIB_ARCH STREQUAL "cbuilder") AND NOT (MXSRCLIB_ARCH STREQUAL "dos32") AND
Зачем эта портянка тут

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +string(FIND ${CMAKE_CXX_COMPILER} "/" INDEX_START REVERSE)
Зачем?

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +if(NOT (MXSRCLIB_ARCH STREQUAL "none"))
Зачем? Падай с ошибкой если для архитектуры не написан switch

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +    # Для корректной работы архитектуры srm_st_hal необходимо подключить arm архитектуру
srm?

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +# Если выбран кросс-компилятор, то попытаться сконвертировать как статическую библиотеку,
скомпилировать а не сконвертировать

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +    if(NOT (MXSRCLIB_ARCH STREQUAL "none"))
Архитектура должна проверяться на none 1 раз. И если none то падать с ошибкой. В остальных случаях эта проверка не нужна

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +        list(APPEND CONVERTED_MXSRCLIB_HEADERS "${CONVERTED_MXSRCLIB_HEADERS_DIR}/arch/arm")
А нельзя выше то список с хэдерами сделать? Зачем 20 раз писать свитч на архитектуру?

2024-06-04 11:26 UTC, Feelinglight commented on .gitignore
> +converted_headers/*.h
А папку просто добавить нельзя?

2024-06-04 11:26 UTC, Feelinglight commented on CMakeLists.txt
> +    add_dependencies(mxsrclib converted_headers)
Это так и надо mxsrclib сюда добавлять?

2024-06-04 11:57 UTC, injecktor commented on .gitignore
> +converted_headers/*.h
Так там же cmake

2024-06-04 12:23 UTC, injecktor commented on CMakeLists.txt
> +    add_dependencies(mxsrclib converted_headers)
Да. Для срабатывая кастомных команд необходимо, чтобы кто-то зависел от converted_headers

2024-06-04 12:25 UTC, injecktor commented on CMakeLists.txt
> +    message(STATUS "MXSRCLIB_ARCH: ${MXSRCLIB_ARCH}")
Сделал, чтобы это выводилось только в режиме VERBOSE

2024-06-04 13:00 UTC, injecktor commented on CMakeLists.txt
> +string(FIND ${CMAKE_CXX_COMPILER} "/" INDEX_START REVERSE)
На разных системах месторасположение компилятора будет разным, а CMAKE_CXX_COMPILER
хранит в себе полный путь.

От компилятора зависят флаги, которые ему передаются.  Для того, чтобы писать свитч на него,
нужно получить чистое имя

2024-06-04 13:57 UTC, Feelinglight commented on .gitignore
> +converted_headers/*.h
folder/*
!folder/file

2024-06-05 07:08 UTC, Feelinglight requested changes

2024-06-05 07:08 UTC, Feelinglight commented on CMakeLists.txt
> +elseif(MXSRCLIB_ARCH STREQUAL "arm_st_hal")
Сделай пустую строку перед каждым elseif

2024-06-05 07:08 UTC, Feelinglight commented on CMakeLists.txt
> +string(FIND ${CMAKE_CXX_COMPILER} "/" INDEX_START REVERSE)
А нельзя просто matches использовать?
https://stackoverflow.com/questions/28532444/cmake-string-token-inclusion-check

2024-06-05 07:08 UTC, Feelinglight commented on CMakeLists.txt
> +    target_link_libraries(mxsrclib stm32cubef7)
А почему мы вдруг куб требуем безусловно?

2024-06-05 07:37 UTC, injecktor commented on .gitignore
> +converted_headers/*.h
И так, и так две строки, но сделал.

2024-06-05 12:41 UTC, injecktor commented
Добавил переменную с таргетом для библиотек архитектуры

2024-06-05 13:16 UTC, Feelinglight requested changes
Доделать документацию

2024-06-06 06:32 UTC, Feelinglight requested changes

2024-06-06 06:32 UTC, Feelinglight commented on docs/src/docs.md
> +В директории **convert_mxsrclib_headers** находится cmake файл с конвертацией заголовков
Неактуальное имя

2024-06-06 06:32 UTC, Feelinglight commented on docs/src/docs.md
> +## Использование
Здесь нужно просто пример подключения

2024-06-06 06:32 UTC, Feelinglight commented on docs/src/docs.md
> +  Стандартного значения нет.
Не надо это писать. Нужно писать только если есть. И не стандартное, а значение по умолчанию

2024-06-06 06:32 UTC, Feelinglight commented on docs/src/docs.md
> +  помимо основных.
Папка с архитектурно зависимым кодом

2024-06-06 06:32 UTC, Feelinglight commented on docs/src/docs.md
> +  Конвертировать cp1251 заголовки mxsrclib в utf-8.
Об этом нужно отдельный раздел. Зачем это нужно и как реализовано

2024-06-07 07:50 UTC, Feelinglight approved these changes

2024-06-07 07:50 UTC, merged