Arm support
irsural/mxsrclib pull request #5
Opened 2024-06-11 10:59 UTC by injecktor

2024-06-13 07:53 UTC, Feelinglight requested changes

2024-06-13 07:53 UTC, Feelinglight commented on irsdefsbase.h
> +#define IRS_STATIC_ASSERT(ex)\
Это зачем? Проверь пулл реквест на ненужные изменения.

2024-06-13 07:53 UTC, Feelinglight commented on irsdefsbase.h
> +#endif
Объявляй ниже в дефайне __GNUC__ по elif на IRS_CORTEX_M

2024-06-13 07:53 UTC, Feelinglight commented on hardflowg.cpp
> +#if defined(WIN32) || defined(_WIN32) || defined(IRS_GCC_CORTEX_M)
Здесь не надо. Найди способ включить функцию cstr_to_mxip

2024-06-17 13:17 UTC, injecktor commented on hardflowg.cpp
> +#if defined(WIN32) || defined(_WIN32) || defined(IRS_GCC_CORTEX_M)
Она и так включается. Мне необходимо входить именно в это if потому, что в else находится функция narrow, 
которая определяется только для линукса и винды

2024-06-18 07:41 UTC, Feelinglight requested changes

2024-06-18 07:41 UTC, Feelinglight commented on irsdefsbase.h
> +#ifndef IRS_GCC_CORTEX_M
А else отменили или как?

2024-06-18 07:41 UTC, Feelinglight commented on hardflowg.cpp
> +#if defined(WIN32) || defined(_WIN32) || defined(IRS_GCC_CORTEX_M)
Нужно не дефайнить все что попало, а разобраться в ситуации и сделать как надо. Если непонятно как надо, то спросить.

Удали обе функции narrow и все ifdef-ы, которые с ней связаны.
Везде должно остаться просто ``cstr_to_mxip(new_ip, IRS_SIMPLE_FROM_TYPE_STR(a_value.c_str()));``

2024-06-18 07:44 UTC, Feelinglight commented on irsdefsbase.h
> +#ifndef IRS_GCC_CORTEX_M
И сделай 
```cpp
# ifdef 
// ...
# elseif
// ...
# else
#error Платформа не определена
# ...
```

2024-06-25 07:42 UTC, Feelinglight requested changes

2024-06-25 07:42 UTC, Feelinglight commented on hardflowg.cpp
> +      gethostbyname(IRS_SIMPLE_FROM_TYPE_STR(a_adress_str.c_str()));
Отступ неправильный

2024-06-25 07:42 UTC, Feelinglight commented on irsdefsbase.h
>  #define IRS_LINUX // ��������� Linux
Ниче не понял. Почему здесь else? Почему ошибка Платформа не определена сделана при отсутствии поддерживаемого компилятора? Здесь нужно проверять [ПЛАТФОРМУ](https://stackoverflow.com/questions/30139983/how-do-i-identify-x86-vs-x86-64-at-compile-time-in-gcc).

2024-06-25 13:38 UTC, Feelinglight requested changes
Исправить irsconfig

2024-06-25 13:47 UTC, Feelinglight approved these changes

2024-06-25 13:48 UTC, merged